config/routes.rb
Nolaattractions::Application.routes.draw do
  root 'attractions#index'
  resources :attractions

end

app/models/attraction.rb
class Attraction < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController

	def index
		@attractions = Attraction.all
	end

	def new
		@attractions = Attraction.new
	end

	def create
		Attraction.create(attractions_params)
		redirect_to root_path
	end

	private

	def attractions_params
		params.require(:attraction).permit(:name, :description, :address)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/index.html.erb
<% @attractions.each do |attraction| %>
  <div class="box">
    <h1><%= attraction.name %></h1><br />
    <i><%= attraction.address %></i><br />
    <p><%= attraction.description %></p><br />
  </div>

  
<% end %>

app/views/attractions/new.html.erb
<div class="box col-xs-10 col-xs-offset-1">
  <h1>Got a favorite attraction in NOLA? Enter it here!</h1>
  <br />
  <%= simple_form_for @attractions do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-success' %> %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nolaattractions</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to 'NolAAttractions', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
      <%= link_to 'Enter your favorite attraction', new_attraction_path %>
    	</li>
     </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>